---
title: "CA Girls' Average Daily Population Fact Sheet"
author: "Shaina Mackin | The Vera Institute"
date: "March 29, 2022"
output: github_document
---

```{r setup, echo=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(plotly)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r import, echo = FALSE, message = FALSE, warning = FALSE}
adp_df = read_excel("./data/juvenile_adp_2002-2021.xlsx", col_types = "text") 
```

```{r tidy, echo=FALSE, message = FALSE, warning = FALSE}
adp_girls = adp_df %>%
  janitor::clean_names() %>%
  mutate(
    adp_pre_disposition_female = replace(adp_pre_disposition_female, adp_pre_disposition_female == "D", 0),
    adp_pre_disposition_female = replace(adp_pre_disposition_female, adp_pre_disposition_female == "d", 0),
     adp_pre_disposition_female = replace(adp_pre_disposition_female, adp_pre_disposition_female == "u", 0),
     adp_post_disposition_female = replace(adp_post_disposition_female, adp_post_disposition_female == "D", 0),
     adp_post_disposition_female = replace(adp_post_disposition_female, adp_post_disposition_female == "d", 0),
    adp_post_disposition_female = replace(adp_post_disposition_female, adp_post_disposition_female == "u", 0),
  ) %>%
  select(county, year, month, adp_pre_disposition_female, adp_post_disposition_female) %>%
  mutate(
    adp_pre_disposition_female = as.numeric(adp_pre_disposition_female),
    adp_post_disposition_female = as.numeric(adp_post_disposition_female)) %>%
  mutate(
    total_female = adp_pre_disposition_female + adp_post_disposition_female) %>%
    group_by(county, year, month) %>%
  summarise(
    adp_pre_disposition_female = sum(adp_pre_disposition_female),
    adp_post_disposition_female = sum(adp_post_disposition_female),
    total_female = sum(total_female)) %>%
  mutate(
    year = as.numeric(unlist(year)),
    month = as.numeric(unlist(month)),
    day = "01"
    ) %>%
  mutate(
    month = formatC(as.numeric(month), width=2,format='f',digits = 0, flag='0') 
  ) %>%
  select(county, day, month, year, total_female) %>%
  unite('the_date', day:year, remove = FALSE) %>%
  mutate(
    the_date = str_replace(the_date, "_", "\\")
  ) %>%
   mutate(
    the_date = str_replace(the_date, "_", "\\")
  ) %>%
  mutate(
    the_date = lubridate::dmy(the_date)
  )

write.csv(adp_girls,"/Users/shainamackin/Desktop/Vera/California Criminalization/data/adp_girls.csv")
```

```{r annual_adp, echo = FALSE, message = FALSE}
annual_adp = adp_girls %>%
  select(county, month, year, total_female) %>%
  group_by(county, year) %>%
  summarize(annual = sum(total_female))

annual_2021_plot = annual_adp %>%
  filter(year == 2021) %>%
  ggplot(aes(x = reorder(county, -annual), y = annual, fill = annual)) +
  geom_bar(position="dodge", stat="identity") +
  theme(legend.position=c(0.9, 0.8)) +
  labs(
    title = "Annual Sum of Monthly ADP by CA County, 2021",
    x = "County",
    y = "Annual ADP Sum") +
  theme(axis.text.x=element_text(angle = 90, hjust = 1))

annual_2021_plot
```


```{r months, include = FALSE, echo=FALSE, message = FALSE, warning= FALSE}
jan_2021 = adp_girls %>%
  filter(year == 2021 & month == '01')

feb_2021 = adp_girls %>%
  filter(year == 2021 & month == '02')

mar_2021 = adp_girls %>%
  filter(year == 2021 & month == '03')

plot_jan_2021 = jan_2021 %>%
  mutate(ADP = total_female) %>%
  ggplot(aes(x = reorder(county, -total_female), y = ADP, fill = county)) +
  geom_bar(position="dodge", stat="identity") +
  labs(
    title = "Average Daily Population of Girls in Californian Facilities: Jan 1, 2021",
    x = "County",
    y = "ADP") +
  theme(axis.text.x=element_text(angle = 90, hjust = 1))

plot_feb_2021 = feb_2021 %>%
  mutate(ADP = total_female) %>%
  ggplot(aes(x = reorder(county, -total_female), y = ADP, fill = county)) +
  geom_bar(position="dodge", stat="identity") +
  labs(
    title = "Average Daily Population of Girls in Californian Facilities: Feb 1, 2021",
    x = "County",
    y = "ADP") +
  theme(axis.text.x=element_text(angle = 90, hjust = 1))

plot_mar_2021 = mar_2021 %>%
  mutate(ADP = total_female) %>%
  ggplot(aes(x = reorder(county, -total_female), y = ADP, fill = county)) +
  geom_bar(position="dodge", stat="identity") +
  labs(
    title = "Average Daily Population of Girls in Californian Facilities: Mar 1, 2021",
    x = "County",
    y = "ADP") +
  theme(axis.text.x=element_text(angle = 90, hjust = 1))
  
```

```{r santa_clara_county, echo = FALSE}
scc_2020 = adp_girls %>%
  filter(county == "Santa Clara" & year == 2020) %>%
  mutate(
    month = as.factor(month),
    day = as.numeric(day),
    year = as.numeric(year),
    ADP = total_female)

scc_2020 %>%
  ggplot(aes(x = month, y = ADP, fill = ADP)) +
  geom_bar(position="dodge", stat="identity") +
    theme(legend.position=c(0.9, 0.8)) +
  labs(
    title = "ADP of Girls in Santa Clara County Facilities, 2020",
    x = "Month",
    y = "ADP") +
  theme(axis.text.x=element_text(angle = 90, hjust = 1))


scc_2021 = adp_girls %>%
  filter(county == "Santa Clara" & year == 2021) %>%
  mutate(
    month = as.factor(month),
    day = as.numeric(day),
    year = as.numeric(year),
    ADP = total_female)

scc_2021 %>%
  ggplot(aes(x = month, y = ADP, fill = ADP)) +
  geom_bar(position="dodge", stat="identity") +
    theme(legend.position=c(0.9, 0.8)) +
  labs(
    title = "ADP of Girls in Santa Clara County Facilities, 2021",
    x = "Month",
    y = "ADP") +
  theme(axis.text.x=element_text(angle = 90, hjust = 1))

```

